name: event_planr_app
description: Event planer application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_flutter: ^1.0.0
  card_swiper: ^3.0.1
  dio: ^5.3.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_screenutil: ^5.9.0
  flutter_web_plugins:
    sdk: flutter
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^10.2.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  pretty_qr_code: ^3.0.0
  responsive_framework: ^1.1.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  swagger_parser: ^1.10.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
    - assets/icon/
