name: event_planr
description: Event planner application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.3.0
  bloc: ^8.1.1
  dio: ^5.1.1
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^8.5.0
  get_it: ^7.2.0
  go_router: ^6.5.5
  http: ^0.13.5
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  pretty_qr_code: ^2.0.3
  retrofit: ^4.0.1
  shared_preferences: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+3
  very_good_analysis: ^4.0.0   

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
    - assets/icon/
