name: Backend CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
        - backend/**
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  WORKING_DIRECTORY: 'backend'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
