name: Backend Deploy

on:
  push:
    branches: [ "main" ]
    paths:
        - backend/**
        - infrastructure/backend/**
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: '1.5.6'
  DOTNET_VERSION: '6.0.x'

jobs:
  backend-deploy:
    name: Backend deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infrastructure/backend/main'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'backend'
      
    - name: Release build
      run: dotnet build --configuration Release --no-restore
      working-directory: 'backend'

    - name: Publish Lambda projects
      run: sh publish_lambda_services.sh
      working-directory: 'infrastructure/backend'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Workspace
      run: terraform workspace select production

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
