name: Frontend Analyze

on:
  pull_request:
    branches: [ "main" ]
    paths:
        - frontend/**
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.13.0'

jobs:
  frontend-analyze:
    name: Frontend Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build

      - name: Analyze project
        run: flutter analyze --fatal-infos
