name: Frontend Infrastructure Deploy

on:
  push:
    branches: [ "main" ]
    paths:
        - infrastructure/frontend/**
        - frontend/**
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: '1.5.6'

jobs:
  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infrastructure/backend/main'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Workspace
      run: terraform workspace select production

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

  app-upload:
    needs: deploy-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
            parameterPairs: "/production/event_planr/awsRegion = AWS_REGION,
                /production/event_planr/eventPlanrApiUrl = EVENT_PLANR_API_URL,
                /production/event_planr/cognitoPoolId = COGNITO_POOL_ID,
                /production/event_planr/cognitoPoolClientId = COGNITO_POOL_CLIENT_ID,
                /production/event_planr/chatMessageGraphqlUrl = CHAT_MESSAGE_GRAPHQL_URL,
                /production/event_planr/nominatimApiUrl = NOMINATIM_API_URL,
                /production/event_planr/frontendBucket = FRONTEND_BUCKET"
            withDecryption: "true"

      - name: Create .env file
        run: |
          touch .env.prod
          echo AWS_REGION="$AWS_REGION" >> .env.prod
          echo EVENT_PLANR_API_URL="$EVENT_PLANR_API_URL" >> .env.prod
          echo COGNITO_POOL_ID="$COGNITO_POOL_ID" >> .env.prod
          echo COGNITO_POOL_CLIENT_ID="$COGNITO_POOL_CLIENT_ID" >> .env.prod
          echo CHAT_MESSAGE_GRAPHQL_URL="$CHAT_MESSAGE_GRAPHQL_URL" >> .env.prod
          echo NOMINATIM_API_URL="$NOMINATIM_API_URL" >> .env.prod

      - name: Create web build
        run: flutter build web --target lib/main_production.dart --dart-define-from-file .env.prod --output web_build

      - name: Create app build
        run: flutter build apk --target lib/main_production.dart --dart-define-from-file .env.prod --output android_build

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.FRONTEND_BUCKET }}
          source_dir: 'web_build'

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.FRONTEND_BUCKET }}
          source_dir: 'android_build'
